### ISSUE TITLE
Test the Main Function

### ISSUE THREAD

**Issue by juliaross20** [polortiz4/bme590_assignment02#24]
We are sure that all of the functions within main work because they have all been unit tested but I'm not positive they all work together and I'm struggling to test this. Could we have some help? It's called main.py btw

**Comment by suyashkumar** [comment]
Hi Julia, glad to hear that all your unit tests work! If you've written tests for all your module functions, I'd say you've hit the target on generally what's expected out of unit tests. If all those tested functions are combined, you can now expect that they should behave as expected.

However, your intuition to ensure that the tested functions are combined in a proper way to accomplish the goal is a fantastic one. The scope here is a little larger, but essentially involves what is known as an **integration test** which is described as "integration tests show that the major parts of a system work well together" [here](https://softwareengineering.stackexchange.com/questions/48237/what-is-an-integration-test-exactly). This is a type of software test.

This testing is important because if someone comes along to your `main` function and messes with the code in a way that breaks it's intended processing, you'd want to make sure that your test procedures fail in some way to prevent that regression from happening unnoticed.

One way to do this for the code you've written is to call `main(filename, mins)` with a test file and then to check that the expected output got written to disk. So your test would do the following:
- call `main(filename, mins)` with a test file and `mins`
- assert that the proper file was written to disk
- assert that the file contents are what you expect. This could be done by comparing it to a file you know is good output for the input test data file.
